/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import agentesc.Contenedor;
import static java.lang.System.exit;
import javax.swing.JOptionPane;

/**
 *
 * @author pavox20
 */
public class GUI extends javax.swing.JFrame {
//public static Cliente cliente;

    /**
     * Creates new form NewJFrame
     */
    public GUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        JOptionPane.showMessageDialog(null, "Dear user ❤"
                + "\nPlease before use the program read the manual located at File>Help");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        Buttom = new javax.swing.JButton();
        Destination = new javax.swing.JComboBox<>();
        Airline = new javax.swing.JComboBox<>();
        Source = new javax.swing.JComboBox<>();
        Months = new javax.swing.JComboBox<>();
        Day = new javax.swing.JComboBox<>();
        Stops = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(860, 390));
        setSize(new java.awt.Dimension(860, 390));
        getContentPane().setLayout(null);

        jLabel13.setFont(new java.awt.Font("Savoye LET", 1, 48)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Airplane tickets prices");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel13);
        jLabel13.setBounds(180, 0, 550, 70);

        jLabel17.setText("Airline:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(30, 80, 130, 17);

        jLabel25.setText("Source");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(30, 120, 130, 17);

        jLabel29.setText("Destination");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(30, 160, 140, 17);

        jLabel30.setText("Stops:");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(30, 200, 140, 17);

        jLabel31.setText("Month:");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(30, 280, 140, 17);

        jLabel33.setText("Day:");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(30, 240, 50, 17);

        Buttom.setText("Calculate price");
        Buttom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        Buttom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtomActionPerformed(evt);
            }
        });
        getContentPane().add(Buttom);
        Buttom.setBounds(590, 160, 120, 30);

        Destination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not selected", "Banglore", "Cochin", "Delhi", "Hyderabad", "Kolkata", "New Delhi" }));
        Destination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestinationActionPerformed(evt);
            }
        });
        getContentPane().add(Destination);
        Destination.setBounds(160, 160, 140, 23);

        Airline.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not selected", "Air Asia", "Air India", "GoAir", "IndiGo", "Jet Airways", "Jet Airways Business", "Multiple carriers", "Multiple carriers Premium economy", "SpiceJet", "Trujet", "Vistara", "Vistara Premium economy" }));
        Airline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AirlineActionPerformed(evt);
            }
        });
        getContentPane().add(Airline);
        Airline.setBounds(160, 80, 140, 23);

        Source.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not selected", "Banglore", "Chennai", "Delhi", "Kolkata", "Mumbai" }));
        Source.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SourceActionPerformed(evt);
            }
        });
        getContentPane().add(Source);
        Source.setBounds(160, 120, 140, 23);

        Months.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Selected", "January", "Febrary", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        Months.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthsActionPerformed(evt);
            }
        });
        getContentPane().add(Months);
        Months.setBounds(160, 280, 140, 23);

        Day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Selected", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        Day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DayActionPerformed(evt);
            }
        });
        getContentPane().add(Day);
        Day.setBounds(160, 240, 140, 23);

        Stops.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Selected", "non-stop", "1 stop", "2 stops", "3 stops", "4 stops" }));
        Stops.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopsActionPerformed(evt);
            }
        });
        getContentPane().add(Stops);
        Stops.setBounds(160, 200, 140, 23);

        jMenu1.setText("File");

        jMenuItem6.setText("Help");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem1.setText("Close");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("About");

        jMenuItem5.setText("About this program");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        JOptionPane.showMessageDialog(null, "Model and Java program was created on an  M1 Pro.");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void ButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtomActionPerformed


        //System.out.println(Aerolinea.getSelectedItem().toString());
        new Contenedor().contenedor();        
        
        JOptionPane.showMessageDialog(null, "Datos ingresados con éxito...");
        

    }//GEN-LAST:event_ButtomActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        help h = new help();
        h.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void DestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DestinationActionPerformed

    private void AirlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AirlineActionPerformed

    private void SourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SourceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SourceActionPerformed

    private void MonthsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonthsActionPerformed

    private void DayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DayActionPerformed

    private void StopsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StopsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> Airline;
    public javax.swing.JButton Buttom;
    public javax.swing.JComboBox<String> Day;
    public javax.swing.JComboBox<String> Destination;
    public javax.swing.JComboBox<String> Months;
    public javax.swing.JComboBox<String> Source;
    public javax.swing.JComboBox<String> Stops;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    // End of variables declaration//GEN-END:variables
}
